### ISSUE TITLE
Move sample from winforms folder to windowsforms sample.

### ISSUE THREAD

**Issue by Thraka** [dotnet/samples#2884]
This issue is here to track the steps involved in moving the Formatting Utility sample from the `winforms` folder to the `windowsforms` folder.

- [x] Instead of moving the content, you need to clone the content into the new place and update the `urlFragment` in the metadata for both the VB and CS readme files. Change the part that is `winforms` to `windowsforms` (@augustoproiete #2881) 
- [x] Publish the sample (@thraka #2885)
- [x] File an issue in the dotnet/docs repo to update links to the sample to the new location (@thraka dotnet/docs#18374)
- [ ] File an issue in the dotnet/dotnet-api-docs repo to update links to the sample to the new location (@thraka dotnet/dotnet-api-docs#4220)
- [ ] Delete the sample from the winforms folder (@augustoproiete or @Youssef1313)

**Comment by Thraka** [comment]
@augustoproiete You can open the PR to delete the sample, just note that it shouldn't be merged until the rest of the steps on this issue are completed.

**Comment by augustoproiete** [comment]
Thanks @Thraka. PR #2887 created to remove the files
